export const NEW_EPISODIES_MOCK = [
  {
    title: 'Renai Flops',
    name: 'renai-flops',
    episode: '2',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3708.jpg',
    link: 'https://www3.animeflv.net/ver/renai-flops-2',
  },
  {
    title: 'Tensei shitara Ken Deshita',
    name: 'tensei-shitara-ken-deshita',
    episode: '4',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3676.jpg',
    link: 'https://www3.animeflv.net/ver/tensei-shitara-ken-deshita-4',
  },
  {
    title: 'Futoku no Guild',
    name: 'futoku-no-guild',
    episode: '3',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3695.jpg',
    link: 'https://www3.animeflv.net/ver/futoku-no-guild-3',
  },
  {
    title: 'Do It Yourself!!',
    name: 'do-it-yourself',
    episode: '3',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3694.jpg',
    link: 'https://www3.animeflv.net/ver/do-it-yourself-3',
  },
  {
    title: 'Kage no Jitsuryokusha ni Naritakute!',
    name: 'kage-no-jitsuryokusha-ni-naritakute',
    episode: '3',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3690.jpg',
    link: 'https://www3.animeflv.net/ver/kage-no-jitsuryokusha-ni-naritakute-3',
  },
  {
    title: 'Mob Psycho 100 III',
    name: 'mob-psycho--iii',
    episode: '3',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3691.jpg',
    link: 'https://www3.animeflv.net/ver/mob-psycho-100-iii-3',
  },
  {
    title: 'Shine Post',
    name: 'shine-post',
    episode: '12',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3664.jpg',
    link: 'https://www3.animeflv.net/ver/shine-post-12',
  },
  {
    title: 'Yama no Susume: Next Summit',
    name: 'yama-no-susume-next-summit',
    episode: '3',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3689.jpg',
    link: 'https://www3.animeflv.net/ver/yama-no-susume-next-summit-3',
  },
  {
    title: 'Chainsaw Man',
    name: 'chainsaw-man',
    episode: '2',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3707.jpg',
    link: 'https://www3.animeflv.net/ver/chainsaw-man-2',
  },
  {
    title: 'Vazzrock The Animation',
    name: 'vazzrock-the-animation',
    episode: '3',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3688.jpg',
    link: 'https://www3.animeflv.net/ver/vazzrock-the-animation-3',
  },
  {
    title: 'Shinobi no Ittoki',
    name: 'shinobi-no-ittoki',
    episode: '3',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3687.jpg',
    link: 'https://www3.animeflv.net/ver/shinobi-no-ittoki-3',
  },
  {
    title: 'Bleach: Sennen Kessen-hen',
    name: 'bleach-sennen-kessenhen',
    episode: '2',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3704.jpg',
    link: 'https://www3.animeflv.net/ver/bleach-sennen-kessenhen-2',
  },
  {
    title: 'Golden Kamuy 4th Season',
    name: 'golden-kamuy-th-season',
    episode: '3',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3686.jpg',
    link: 'https://www3.animeflv.net/ver/golden-kamuy-4th-season-3',
  },
  {
    title: 'Shinmai Renkinjutsushi no Tenpo Keiei',
    name: 'shinmai-renkinjutsushi-no-tenpo-keiei',
    episode: '3',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3685.jpg',
    link: 'https://www3.animeflv.net/ver/shinmai-renkinjutsushi-no-tenpo-keiei-3',
  },
  {
    title: 'Peter Grill to Kenja no Jikan: Super Extra',
    name: 'peter-grill-to-kenja-no-jikan-super-extra',
    episode: '2',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3705.jpg',
    link: 'https://www3.animeflv.net/ver/peter-grill-to-kenja-no-jikan-super-extra-2',
  },
  {
    title: 'Fuuto Tantei',
    name: 'fuuto-tantei',
    episode: '12',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3669.jpg',
    link: 'https://www3.animeflv.net/ver/fuuto-tantei-12',
  },
  {
    title: 'IDOLiSH7: Third Beat!',
    name: 'idolish-third-beat',
    episode: '16',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3474.jpg',
    link: 'https://www3.animeflv.net/ver/idolish7-third-beat-16',
  },
  {
    title: 'Fuufu Ijou, Koibito Miman.',
    name: 'fuufu-ijou-koibito-miman',
    episode: '2',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3706.jpg',
    link: 'https://www3.animeflv.net/ver/fuufu-ijou-koibito-miman-2',
  },
  {
    title: 'Digimon Ghost Game',
    name: 'digimon-ghost-game',
    episode: '47',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3522.jpg',
    link: 'https://www3.animeflv.net/ver/digimon-ghost-game-47',
  },
  {
    title: 'Mobile Suit Gundam: The Witch from Mercury',
    name: 'mobile-suit-gundam-the-witch-from-mercury',
    episode: '3',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/thumbs/3684.jpg',
    link: 'https://www3.animeflv.net/ver/mobile-suit-gundam-the-witch-from-mercury-3',
  },
];

export const EPISODE_LINK_MOCK = [
  {
    title: 'mega',
    link: 'https://mega.nz/embed#!stN1GJBJ!JDKOCbiR7V51vabtf1OkLqjJ76y_Wp3XG7sB--q6KeU',
  },
  {
    title: 'fembed',
    link: 'https://mega.nz/embed#!stN1GJBJ!JDKOCbiR7V51vabtf1OkLqjJ76y_Wp3XG7sB--q6KeU',
  },
];

export const SERIES_MOCK = [
  {
    name: 'KanColle: Itsuka Ano Umi de',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3713.jpg',
    link: 'https://www3.animeflv.net/anime/kancolle-itsuka-ano-umi-de',
  },
  {
    name: 'Arknights: Reimei Zensou',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3712.jpg',
    link: 'https://www3.animeflv.net/anime/arknights-reimei-zensou',
  },
  {
    name: 'Fumetsu no Anata e 2nd Season',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3711.jpg',
    link: 'https://www3.animeflv.net/anime/fumetsu-no-anata-e-2nd-season',
  },
  {
    name: '4-nin wa Sorezore Uso wo Tsuku',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3710.jpg',
    link: 'https://www3.animeflv.net/anime/4nin-wa-sorezore-uso-wo-tsuku',
  },
  {
    name: 'Urusei Yatsura (2022)',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3709.jpg',
    link: 'https://www3.animeflv.net/anime/urusei-yatsura-2022',
  },
  {
    name: 'Renai Flops',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3708.jpg',
    link: 'https://www3.animeflv.net/anime/renai-flops',
  },
  {
    name: 'Chainsaw Man',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3707.jpg',
    link: 'https://www3.animeflv.net/anime/chainsaw-man',
  },
  {
    name: 'Fuufu Ijou, Koibito Miman.',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3706.jpg',
    link: 'https://www3.animeflv.net/anime/fuufu-ijou-koibito-miman',
  },
  {
    name: 'Peter Grill to Kenja no Jikan: Super Extra',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3705.jpg',
    link: 'https://www3.animeflv.net/anime/peter-grill-to-kenja-no-jikan-super-extra',
  },
  {
    name: 'Bleach: Sennen Kessen-hen',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3704.jpg',
    link: 'https://www3.animeflv.net/anime/bleach-sennen-kessenhen',
  },
  {
    name: 'Yowamushi Pedal: Limit Break',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3703.jpg',
    link: 'https://www3.animeflv.net/anime/yowamushi-pedal-limit-break',
  },
  {
    name: 'Noumin Kanren no Skill bakka Agetetara Nazeka Tsuyoku Natta.',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3702.jpg',
    link: 'https://www3.animeflv.net/anime/noumin-kanren-no-skill-bakka-agetetara-nazeka-tsuyoku-natta',
  },
  {
    name: 'Blue Lock',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3701.jpg',
    link: 'https://www3.animeflv.net/anime/blue-lock',
  },
  {
    name: 'Bocchi the Rock!',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3700.jpg',
    link: 'https://www3.animeflv.net/anime/bocchi-the-rock',
  },
  {
    name: 'Mairimashita! Iruma-kun 3rd Season',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3699.jpg',
    link: 'https://www3.animeflv.net/anime/mairimashita-irumakun-3rd-season',
  },
  {
    name: 'Seiken Densetsu: Legend of Mana - The Teardrop Crystal',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3698.jpg',
    link: 'https://www3.animeflv.net/anime/seiken-densetsu-legend-of-mana-the-teardrop-crystal',
  },
  {
    name: 'Akiba Maid Sensou',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3697.jpg',
    link: 'https://www3.animeflv.net/anime/akiba-maid-sensou',
  },
  {
    name: 'Mushikaburi-hime',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3696.jpg',
    link: 'https://www3.animeflv.net/anime/mushikaburihime',
  },
  {
    name: 'Futoku no Guild',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3695.jpg',
    link: 'https://www3.animeflv.net/anime/futoku-no-guild',
  },
  {
    name: 'Do It Yourself!!',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3694.jpg',
    link: 'https://www3.animeflv.net/anime/do-it-yourself',
  },
  {
    name: 'Muv-Luv Alternative 2nd Season',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3693.jpg',
    link: 'https://www3.animeflv.net/anime/muvluv-alternative-2nd-season',
  },
  {
    name: 'Human Bug Daigaku',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3692.jpg',
    link: 'https://www3.animeflv.net/anime/human-bug-daigaku',
  },
  {
    name: 'Mob Psycho 100 III',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3691.jpg',
    link: 'https://www3.animeflv.net/anime/mob-psycho-100-iii',
  },
  {
    name: 'Kage no Jitsuryokusha ni Naritakute!',
    imageUrl: 'https://www3.animeflv.net/uploads/animes/covers/3690.jpg',
    link: 'https://www3.animeflv.net/anime/kage-no-jitsuryokusha-ni-naritakute',
  },
];
